
-- TRABAJANDO CON DISTINCT

SELECT FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES;

-- AL REALIZAR EL DISTINCT, NOS MUESTRA VALORES UNICOS.
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;

-- AL REALIZAR EL DISTINCT, NOS MUESTRA VALORES UNICOS, EN ESTA CASO EVALÚA LAS DOS COLUMNAS
SELECT DISTINCT DEPARTMENT_ID, JOB_ID FROM EMPLOYEES;




-- PRACTICA
SELECT DISTINCT CITY FROM LOCATIONS;

SELECT DISTINCT DEPARTMENT_ID, JOB_ID FROM EMPLOYEES;
