
-- MOSTRAR EL PRIMER NOMBRE Y EL NUMERO DE TELEFONO
SELECT 
    FIRST_NAME, PHONE_NUMBER
FROM EMPLOYEES;


-- MOSTRAR LOS NOMBRES Y TIPO DE TRABAJO EN MINISCULA
SELECT
    FIRST_NAME AS NOMBRE, JOB_ID AS "Tipo de Trabajo"
FROM EMPLOYEES;


-- TODAS LAS COLUMNAS DE REGIONS
SELECT 
    *
FROM REGIONS;


-- LISTAR LOS NOMBRES DE LA TABLA COUNTRIS
SELECT
    COUNTRY_NAME
FROM COUNTRIES;


-- MOSTRAR DATOS ESPECIFICOS DE LA TABLA LOCATIONS
SELECT
    STREET_ADDRESS AS "Dirección", CITY AS "Ciudad", STATE_PROVINCE AS "Estado"
FROM LOCATIONS;

